name: sh_app
description: "Thrift shopping app."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar_v2: ^4.2.8
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

  #Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  #Bloc
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  #Custom repo
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

