name: sh_app
description: "Thrift shopping app."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  geocoding: ^2.0.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  meta: ^1.11.0
  intl: ^0.19.0
  #Firebase
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.15.8

  #Bloc
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  bloc: ^8.1.4

  #GoogleMaps
  dio: ^5.4.2+1
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.6.0

  #Custom repo
  user_repository:
    path: packages/user_repository
  shop_repository:
    path: packages/shop_repository

  #Maps
  interactive_maps_marker: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
